spring:
  application:
    name: springSession2
  data:
    redis:
      host: 192.168.2.129
      port: 6379
      username: poly
      password: 1234
  session:
    redis:
      flush-mode: on_save

server:
  port: 26000
  servlet:
    session:
      timeout: 10m

